---
default_language_version:
  node: 15.1.0
repos:
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
