[tool.pyright]

include = [
    "gfn/**",
]

exclude = [
    "**/node_modules",
    "**/__pycache__",
]

strict = [

]

typeCheckingMode = "basic"
pythonVersion = "3.10"
typeshedPath = "typeshed"
enableTypeIgnoreComments = true

# This is required as the CI pre-commit does not download the module (i.e. numpy)
#   Therefore, we have to ignore missing imports
reportMissingImports = "none"

reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportPrivateUsage = "warning"
reportUntypedFunctionDecorator = "none"
reportMissingTypeStubs = false
reportUnboundVariable = "warning"
reportGeneralTypeIssues ="none"

[tool.pytest.ini_options]

[tool.poetry]
name = "torchgfn"
version = "0.1.0"
description = "A torch inplementation of GFlowNets"
authors = ["Salem Lahou <salemlahlou9@gmail.com>, Joseph Viviano <joseph@viviano.ca>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
einops = "^0.6.1"
gymnasium = "^0.28.1"
numpy = "torch"

[tool.poetry.group.dev.dependencies]
torchtyping = "^0.1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
