shared:
  module_name: NeuralNet # "NeuralNet", "Tabular", "Uniform", "Zero" | default="NeuralNet"
  n_hidden_layers: 2
  hidden_dim: 256
  activation_fn: relu

detailed_balance:
  forward_looking: False

flowmatching:
  alpha: 1.0

trajectory_balance:
  logZ_init: 0.0
  log_reward_clip_min: -12

sub_tb:
  # weighting choices:
  #     "equal", "equal_within", "geometric", "TB", "DB", "ModifiedDB", "geometric_within"
  #     default="geometric_within"
  weighting: geometric_within
  forward_looking: False
  lamda: 0.9
